elkconfig:
  clustername: ucp
  hosts:
    -
      ip: 192.168.1.121
      port: 9301
      schema: http
    -
      ip: 192.168.1.122
      port: 9301
      schema: http
    -
      ip: 192.168.1.123
      port: 9301
      schema: http

  alias: test
  shards: 5
  replicas: 2
  maxWindow: 10000
  scroll: 60000
  poolSize: 5
server:
  port: 8888
